//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMATracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int id { get; set; }
        public Nullable<bool> VerifyReturn { get; set; }
        public Nullable<bool> PhysicalDamage { get; set; }
        public Nullable<bool> PowerUp { get; set; }
        public Nullable<bool> VerifyLED { get; set; }
        public Nullable<bool> TamperSwitch { get; set; }
        public Nullable<bool> PosSwitch { get; set; }
        public Nullable<bool> CableCut { get; set; }
        public Nullable<bool> SkimAlarm { get; set; }
        public Nullable<bool> CardRead { get; set; }
        public string NFCProximity { get; set; }
        public string UnitPassFail { get; set; }
        public string RootCause { get; set; }
        public string HardwareRootCause { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
