//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMATracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int id { get; set; }
        public Nullable<int> rma_id { get; set; }
        public byte[] Image1 { get; set; }
        public string Description1 { get; set; }
        public byte[] Image2 { get; set; }
        public string Description2 { get; set; }
        public byte[] Image3 { get; set; }
        public string Description3 { get; set; }
        public byte[] Image4 { get; set; }
        public string Description4 { get; set; }
        public byte[] Image5 { get; set; }
        public string Description5 { get; set; }
        public byte[] Image6 { get; set; }
        public string Description6 { get; set; }
        public byte[] Image7 { get; set; }
        public string Description7 { get; set; }
    }
}
