//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMATracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuttyTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuttyTest()
        {
            this.RMAs = new HashSet<RMA>();
        }
    
        public int id { get; set; }
        public Nullable<bool> VerifyComms { get; set; }
        public string MagneticCardReaderTest { get; set; }
        public string NFCProximityTest { get; set; }
        public Nullable<bool> BeaconFunctional { get; set; }
        public string FirmwareVersion { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMA> RMAs { get; set; }
    }
}
