//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMATracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMATrackerEntities : DbContext
    {
        public RMATrackerEntities()
            : base("name=RMATrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<BankInfo> BankInfoes { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PuttyTest> PuttyTests { get; set; }
        public virtual DbSet<ReturnAddress> ReturnAddresses { get; set; }
        public virtual DbSet<RMADetail> RMADetails { get; set; }
        public virtual DbSet<RMA> RMAs { get; set; }
        public virtual DbSet<TechInfo> TechInfoes { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
    }
}
