//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMATracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechInfo()
        {
            this.RMAs = new HashSet<RMA>();
        }
    
        public int id { get; set; }
        public string TechName { get; set; }
        public string TechEmail { get; set; }
        public string TechPhone { get; set; }
        public string ClientName { get; set; }
        public string ClientComplaint { get; set; }
        public byte[] ImageFile { get; set; }
        public string FieldObservation { get; set; }
        public string StepsUndertaken { get; set; }
        public Nullable<bool> ComplaintConfirmed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMA> RMAs { get; set; }
    }
}
